#!/usr/bin/env bash

export PATH="$PATH:/srv/provision/composerbin/vendor/bin"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi
red="\[\033[38;5;9m\]"
green="\[\033[01;32m\]"
blue="\[\033[38;5;4m\]"
yellow="\[\033[38;5;3m\]"
white="\[\033[00m\]"
PS1="${debian_chroot:+($debian_chroot)}${red}\u${green}@${blue}\h${white}:${yellow}\w$ \[\033[0m\]"

cd "/srv/www"
