#!/usr/bin/env bash
set -eo pipefail
PROVISIONER="/srv/provision/${2}"

. "/srv/provision/_provisioners"

if [[ -f $PROVISIONER ]]; then
    ( bash "${PROVISIONER}" >> "${VVV_CURRENT_LOG_FILE}" )
    SUCCESS=$?
	if [ "${SUCCESS}" -eq 0 ]; then
		provisioner_success
		exit 0
	else
		exit 1
	fi
else
	vvv_error " * VVV Tried to run the utility provisioner for '${2}' but ${PROVISIONER} doesn't exist."
	exit 1
fi

provisioner_success
