#!/usr/bin/env bash
# @description Install and configure Nginx
set -eo pipefail

function nginx_register_packages() {
  VVV_PACKAGE_LIST+=(nginx)
}
vvv_add_hook before_packages nginx_register_packages

function nginx_setup() {
  # Create an SSL key and certificate for HTTPS support.
  if [[ ! -e /root/.rnd ]]; then
    vvv_info " * Generating Random Number for cert generation..."
    local vvvgenrnd="$(openssl rand -out /root/.rnd -hex 256 2>&1)"
  fi
  if [[ ! -e /etc/nginx/server-2.1.0.key ]]; then
    vvv_info " * Generating Nginx server private key..."
    local vvvgenrsa="$(openssl genrsa -out /etc/nginx/server-2.1.0.key 2048 2>&1)"
  fi
  if [[ ! -e /etc/nginx/server-2.1.0.crt ]]; then
    vvv_info " * Sign the certificate using the above private key..."
    local vvvsigncert="$(openssl req -new -x509 \
            -key /etc/nginx/server-2.1.0.key \
            -out /etc/nginx/server-2.1.0.crt \
            -days 3650 \
            -subj /CN=*.wordpress-develop.test/CN=*.wordpress.test/CN=*.wordpress-develop.dev/CN=*.wordpress.dev/CN=*.vvv.dev/CN=*.vvv.local/CN=*.vvv.localhost/CN=*.vvv.test 2>&1)"
  fi

  vvv_info " * Setup configuration files..."

  # Copy nginx configuration from local
  vvv_info " * Copying /srv/provision/_config/nginx.conf to /etc/nginx/nginx.conf"
  cp -f "/srv/provision/_config/nginx.conf" "/etc/nginx/nginx.conf"

  vvv_info " * Copying /srv/provision/_config/nginx-wp-common.conf to /etc/nginx/nginx-wp-common.conf"
  cp -f "/srv/provision/_config/nginx-wp-common.conf" "/etc/nginx/nginx-wp-common.conf"

  if [[ ! -d "/etc/nginx/upstreams" ]]; then
    mkdir -p "/etc/nginx/upstreams/"
  fi

  vvv_hook nginx_upstreams

  if [[ ! -d "/etc/nginx/custom-sites" ]]; then
    mkdir -p "/etc/nginx/custom-sites/"
  fi
  vvv_info " * Copying /srv/provision/_config/default.conf to /etc/nginx/custom-sites/default.conf"
  cp -f "/srv/provision/_config/default.conf" "/etc/nginx/custom-sites/default.conf" 1> /dev/null

  if [[ ! -d "/etc/nginx/custom-utilities" ]]; then
    mkdir -p "/etc/nginx/custom-utilities/"
  fi

  if [[ ! -d "/etc/nginx/custom-dashboard-extensions" ]]; then
    mkdir -p "/etc/nginx/custom-dashboard-extensions/"
  fi

  rm -rf /etc/nginx/custom-{dashboard-extensions,utilities}/*

  vvv_info " * Making sure the Nginx log files and folder exist"
  mkdir -p /var/log/nginx/
  touch /var/log/nginx/error.log
  touch /var/log/nginx/access.log
}
export -f nginx_setup

vvv_add_hook after_packages nginx_setup 40

if [ "${VVV_DOCKER}" != 1 ]; then
  vvv_add_hook services_restart "service nginx restart"
fi

function nginx_cleanup() {
  vvv_info " * Cleaning up Nginx configs"
  # Kill previously symlinked Nginx configs
  find /etc/nginx/custom-sites -name 'vvv-auto-*.conf' -exec rm {} \;
}
export -f nginx_cleanup

vvv_add_hook finalize nginx_cleanup
