---
sites:
  sandbox:
    # skip_provisioning: true
    description: "Sandbox"
    repo: https://github.com/bradp/vvv-wp.git
    hosts:
      - sandbox.test

  testing:
    skip_provisioning: true
    description: "Just some testing"
    repo: https://github.com/bradp/vvv-wp.git
    hosts:
      - testing.test

  wp-core:
    skip_provisioning: true
    description: "WordPress Core Development"
    repo: https://github.com/Varying-Vagrant-Vagrants/custom-site-template-develop.git
    hosts:
      - wp-core.test
    custom:
      vcs: git
      site_title: "WordPress Core Development"
      description: "Core development"
      admin_email: admin@example.com
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISABLE_WP_CRON: true
        WP_DEBUG_DISPLAY: false
        WP_DEBUG_LOG: true
        WP_DEBUG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: true
        WP_SCRIPT_DEBUG: true

  wp-meta:
    skip_provisioning: true
    description: "WordPress Meta"
    repo: https://github.com/WordPress/meta-environment.git
    hosts:
      - wp-meta.test
    custom:
      provision_site:
        "wordcamp.test": true
        "wordpressorg.test": true
        "buddypressorg.test": false
        "jobs.wordpressnet.test": false
        "wordpresstv.test": false
      site_title: "WordPress Meta"
      description: "Meta development"
      admin_email: admin@example.com
      wpconfig_constants:
        AUTOMATIC_UPDATER_DISABLED: true
        DISABLE_WP_CRON: true
        WP_DEBUG_DISPLAY: false
        WP_DEBUG_LOG: true
        WP_DEBUG: true
        WP_DISABLE_FATAL_ERROR_HANDLER: false
        WP_SCRIPT_DEBUG: true
